config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  get '/admin/tests', to: 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]
  resources :user_tests, on: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, except: :index do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users, depend: :destroy
  has_and_belongs_to_many :user_tests, depend: :destroy
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(set_badge)

    if @badge.save
      redirect_to admin_badges_path
    else
      render new
    end

  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path

  end

  private

  def set_badge
    params.require(:badge).permit(:title, :img_url, :rule_name )
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :find_badge, only: %i[show]

  def index
    @badges = current_user.badges
  end

  def show
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><img src="<%= badge.img_url %>" alt="" width="15%"></td>
  <td class="align-middle"><%= badge.rule_name %></td>
  <td class="align-middle"><%= link_to 'Show', admin_badge_path(badge), class: "btn btn-primary" %></td>
  <td class="align-middle"><%= link_to 'Delete',
                  admin_badge_path(badge),
                  method: :delete,
                  data: {confirm: 'Are you sure?'},
                  class: "btn btn-primary" %></td>
</tr>

app/views/admin/badges/index.html.erb
<h3 class="mt-5 text-center"> Actual awards </h3>

<%if Badge.exists?%>
  <div>
    <table class="table text-center">
      <tr>
        <th>Name</th>
        <th>Image url</th>
        <th>Type</th>
        <th colspan="2">Actions</th>
      </tr>

      <%= render @badges %>

    </table>
  </div>

<%else%>
  <h2 class="mt-5 text-center"> None awards have been created</h2>
<%end%>

<p class="text-center"> <%= link_to 'Create new awards', new_admin_badge_path, class: 'btn btn-warning ' %></p>

app/views/admin/badges/new.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title  %><br>
    <%= form.text_field :title %>
  </p><br>

  <p>
    <%= form.label :img_url  %><br>
    <%= form.text_field :img_url %>
  </p><br>

  <p>
    <%= form.label :rule_name %><br>
    <%= form.text_field :rule_name %>
  </p>

  <p><%= form.submit class: 'btn btn-warning' %></p>

  <p><%= link_to 'Back to test', admin_tests_path, class: 'btn btn-primary' %></p>

<% end %>

app/views/admin/badges/show.html.erb
<h2 class="text-center">Showing the award</h2>

<div class="text-center">
  <h3 class="mt-5">
    "<%= @badge.title %>" award
  </h3>
  <p>
    <img src="<%= @badge.img_url %>" alt="" width="30%" class="">
  </p>
  <p>
    Rule number:
    <%= @badge.rule_name %>
  </p>
</div>