config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  get '/admin/tests', to: 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]
  resources :user_tests, on: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, except: :index do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :current_question, foreign_key: 'current_question_id', class_name: 'UserTest', dependent: :nullify

  validates :body, presence: true
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges, depend: :destroy

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  PASSING_RESULT = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def result
    100 * self.correct_questions/test.questions.count
  end

  def success?
    result >= PASSING_RESULT
  end

  def test_current_question
    test.questions.count - test.questions.order(:id).where('id > ?', current_question.id).count
  end

  def time_left
    (created_at + (test.timer*60)).to_i * 1000
  end

  def time_over?
    test.has_timer? ? (time_left < Time.now.to_i * 1000) : false
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_update_set_next_question
    self.current_question = next_question if current_question
  end
end

app/controllers/user_tests_controller.rb
class UserTestsController < ApplicationController
  before_action :set_passage_test, only: %i[show update result gist]

  def show
  end

  def update
    @passage_test.accept!(params[:answer_ids]) if params[:answer_ids]

    if @passage_test.completed? || @passage_test.time_over?
      redirect_to result_user_test_path(@passage_test)
    else
      render :show
    end
  end

  def result
    TestsMailer.completed_test(@passage_test).deliver_now

    if @passage_test.success?
       @passage_test.update(completed: true)
       badge_service = BadgeService.new(@passage_test)
       badge_service.check_rule
     end
  end

  def gist
    service = GistQuestionService.new(@passage_test.current_question)
    result = service.call
    gist_url = result.html_url

    flash_options = if service.success?
                      create_gist(gist_url)
                      { notice: t('.success', gist_url: view_context.link_to('Show', gist_url)) }
                    else
                      { alert: t('.failure') }
                    end
    redirect_to @passage_test, flash_options
  end

  private

  def create_gist(url)
    current_user.gists.create(question: @passage_test.current_question, gist_url: url )
  end

  def set_passage_test
    @passage_test = UserTest.find(params[:id])
  end
end

app/helpers/user_tests_helper.rb
module UserTestsHelper
end

app/views/user_tests/result.html.erb
<h1 class="text"><%= t('.header') %></h1>

<p>
  <% if @passage_test.success? %>
    <p class="text-success">
      <b><%= t('.win') %></b>
      <%= t('.result', result: @passage_test.result) %>
    </p>
  <% else %>
    <p class="text-danger">
      <b><%= t('.fail') %></b>
      <%= t('.result', result: @passage_test.result) %>
    </p>
  <% end %>
</p>

<%= link_to t('.back'), tests_path, class: 'btn btn-warning'  %>

app/views/user_tests/show.html.erb
    <h1>
      Passing: <%= @passage_test.test.title %> Test
    </h1>

    <% if @passage_test.test.has_timer? %>
        <div class="timer h2">
          <span class="minutes"></span>
          <span>:</span>
          <span class="seconds"></span>
        </div>
        <%= content_tag :span,'Time is over!', class: 'info-user text text-danger hide', data: { timer: @passage_test.time_left}  %>
    <% end %>

  <div class="card border-primary">
    <div class="card-header">
      <b>
        <%= @passage_test.current_question.body %>
      </b>
    </div>

    <p class="text-danger mt-3 ml-3">
      Questions: <%= @passage_test.test_current_question %>/<%= @passage_test.test.questions.count %>
    </p>

    <div class="progress">
      <%= content_tag :div, "", class: 'progress-bar bg-success progress-bar-striped',
                      data: { current_question: @passage_test.test_current_question,
                              total_questions: @passage_test.test.questions.count },
                      role: 'progressbar',
                      value: @passage_test.test_current_question,
                      max: @passage_test.test.questions.count %>
    </div>

    <div class="card-body">
      <%= form_with url: user_test_path(@passage_test), local: true, method: :put do |form| %>
        <%= form.collection_check_boxes :answer_ids, @passage_test.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object_id}" %>
            <%= b.label %>
          </p>
        <% end %>
    </div>
  </div>

<p><%= link_to 'Add question to my gist', gist_user_test_path(@passage_test), method: :post, class: 'btn btn-info mt-3' %></p>

<%= form.submit 'Next', class: 'btn btn-warning' %>
<% end %>