config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  get '/admin/tests', to: 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]
  resources :user_tests, on: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, except: :index do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  def validate_max_answers
    errors.add(:base, 'You can have from 1 to 4 responses') if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users, depend: :destroy
  has_and_belongs_to_many :user_tests, depend: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  default_scope { order :title }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :current_question, foreign_key: 'current_question_id', class_name: 'UserTest', dependent: :nullify

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User"
  has_many :questions, dependent: :destroy
  has_many :user_tests, dependent: :nullify
  has_many :users, through: :user_tests

  scope :easy, -> { where(level: (0..1)) }
  scope :middle, -> { where(level: (2..4)) }
  scope :hard, -> { where(level: (5..Float::INFINITY)) }
  scope :test_by_category, ->(category) { joins(:category).where("categories.title = ?", category) }
  scope :test_by_level, ->(level) {where("level = ?", level)}

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.tests_names_by_category(category)
    test_by_category(category).order(title: :desc).pluck(:title)
  end
  
  def has_timer?
    !timer.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :validatable
  has_many :author_tests, class_name: "Test", foreign_key: :author_id
  has_many :user_tests, dependent: :nullify
  has_many :tests, through: :user_tests
  has_many :gists, dependent: :destroy
  has_many :feedbacks
  has_and_belongs_to_many :badges, depend: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true

  def passage_test(test)
    user_tests.order(id: :desc).find_by(test_id: test.id)
  end

  def test_by_level(level)
    tests.where(level: level)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges, depend: :destroy

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  PASSING_RESULT = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def result
    100 * self.correct_questions/test.questions.count
  end

  def success?
    result >= PASSING_RESULT
  end

  def test_current_question
    test.questions.count - test.questions.order(:id).where('id > ?', current_question.id).count
  end

  def time_left
    (created_at + (test.timer*60)).to_i * 1000
  end

  def time_over?
    test.has_timer? ? (time_left < Time.now.to_i * 1000) : false
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_update_set_next_question
    self.current_question = next_question if current_question
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :find_badge, only: %i[show]

  def index
    @badges = current_user.badges
  end

  def show
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    if @test.questions.present?
      current_user.tests.push(@test)
      redirect_to current_user.passage_test(@test)
    else
      redirect_to root_path, notice: "Sorry, Test doesn't consist any question"
    end  
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author_name, repo_name)
    link_to "Author: #{author_name}", "https://github.com/#{author_name}/#{repo_name}", target: :blank
  end

  def flash_message(key)
    if flash[key]
      content_tag :p, flash[key], class: 'flash message'
    end
  end

  def gist_hash(gist)
    gist.gist_url.split('/').last
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit '#{question.test.title}' Question"
    else
      "Create New #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_tests_helper.rb
module UserTestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-secondary">
  <%= link_to "TestGuru", admin_root_path, class: 'navbar-brand logo'%>

  <span class="navbar-text">
    Welcome, <b><%= current_user.first_name %></b> Guru |
    <div class="btn btn-warning">
      <%= link_to "User panel", root_path%> |
      <%= link_to "Gists", admin_gists_path %> |
      <%= link_to "Awards", admin_badges_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  </span>
</nav>

app/views/layouts/_footer.html.erb
<nav class="footer row-fluid navbar-light bg-success mt-3">
  <span class="navbar-text ml-3">

    Educational project at the online school  <a href="https://thinknetica.com/" target="_blank">Thinknetica</a>
    by <%= github_url('Croud9', 'TestGuru') %>
    <p> Moscow <%= current_year %></p>
  </span>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-success">
  <%= link_to "testGuru", root_path, class: 'navbar-brand logo' %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <b> Welcome, <%= current_user.email %> <%= link_to 'Guru', root_path %></b> |
      <div class='btn btn-warning'>
        <% if current_user.admin? %>
          <%= link_to 'Admin panel', admin_root_path %> |
      <%end %>
        <%= link_to 'Feedback ', new_feedback_path %> |
        <%= link_to 'Awards ', badges_path %> |
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
      </div>
    <%else %>
      <%= link_to 'Sign Up', new_user_registration_path %> |
      <%= link_to 'Log In', new_user_session_path %>
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fir=no">

    <title>Admin | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>

    <div class="container mt-3">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fir=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container mt-3">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do  %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <% flash_key = key == 'notice' ? 'success' : 'danger' %>
  <%= content_tag :p, message.html_safe, class: "alert alert-#{flash_key}" %>
<% end %>