config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  get '/admin/tests', to: 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]
  resources :user_tests, on: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, except: :index do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  def validate_max_answers
    errors.add(:base, 'You can have from 1 to 4 responses') if question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

      if @answer.save
        redirect_to admin_question_path(@answer.question)
      else
        render :new
      end
  end

  def update
      if @answer.update(answer_params)
        redirect_to admin_answer_path(@answer), notice: t('.success')
      else
        render :edit
      end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td> <%= answer.body %><br></td>
  <td> <%= link_to t('.show'), admin_answer_path(answer), class: 'btn btn-light' %></td>
  <td> <%= link_to t('.edit'), edit_admin_answer_path(answer), class: 'btn btn-light' %></td>
  <td>  <%= link_to t('.delete'),
                    admin_answer_path(answer),
                    method: :delete,
                    data: { confirm: t('.are_you_sure') },
                    class: 'btn btn-light' %></td>
</tr>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer],local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 5, cols: 50 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-warning' %>
  </p>
<% end %>

<p><%= link_to t('.back_to_question'), admin_question_path(@answer.question), class: 'btn btn-primary' %></p>

app/views/admin/answers/edit.html.erb
<h2><%= t('.header') %></h2><br>

<h2>
  <%= t('.paragraph', body: @answer.question.body) %>
</h2><br>

<%= render 'form' %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<h1>
  <%= t('.paragraph', body: @answer.question.body) %>
</h1>

<%= render 'form' %>

app/views/admin/answers/show.html.erb
<h2>
  <%= t('.question', body: @answer.question.body) %>
</h2><br>

<h2>
  <%= t('.answer', body: @answer.body) %>
</h2><br>

<p>
  <%= t('.correct', correct: @answer.correct) %>
</p>

<%= link_to t('.back_to_question'), admin_question_path(@answer.question), class: 'btn btn-primary' %>